# Manipulating Arrays

Here are two techniques that can be used to change or manipulayte the structure of arrays:
*  Stacking
*  Reshaping

### Stacking

In [2]:
#importing the NumPy library
import numpy as np

# Creating two 1-D arrays with 5 elements using arange
arr_1 = np.arange(5)
arr_2 = np.arange(5,10)


In [5]:
# Horizonal stacking - Appending the elements in the same row
np.hstack((arr_1, arr_2))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
# Vertical stacking - Increasing the number of row
np.vstack((arr_1, arr_2))

# Storing the stacked array for further operations
arr_3 = np.vstack((arr_1, arr_2))
arr_3

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [10]:
# Checking the dimensions of the array
arr_3.ndim

2

In [11]:
# Printing the created array
arr_3


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [12]:
# Number of rows and columns in the array
arr_3.shape

(2, 5)

### Reshaping

In [ ]:
# Creating an array of first ten natural numbers
arr_4 = 

# Printing the created array
arr_4

In [ ]:
# Reshaping the 1D array into a 2D array with 2 elements in five rows
arr_5 = 

In [ ]:
# Checking the rows and columns in the created array
arr_5

In [ ]:
# Creating a 2D array with 4 elements in five rows (elements from 20 to 39)
arr_6 = 

# Checking the rows and columns in the created array
arr_5

In [ ]:
# Stacking arr_5 and arr_6


In [ ]:
# Check the structure of arr_6


In [ ]:
# Reshape the arr_6 to vertically stack with arr_5 
arr_6 = 
arr_6

In [ ]:
# Stacking arr_5 and arr_6
