In [2]:
import numpy as np 

In [3]:
mylist = [1,2,3,4]

In [4]:
type(mylist)

list

In [5]:
arr = np.array(mylist)

In [6]:
arr

array([1, 2, 3, 4])

In [7]:
type(arr)

numpy.ndarray

In [9]:
np.arange(0,10,2) #arange(start,end,step)

array([0, 2, 4, 6, 8])

In [11]:
np.zeros(shape=(10,5)) # shape(rows ,columns)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [12]:
type(0)

int

In [13]:
type(0.)

float

In [14]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [15]:
np.random.seed(101)
arr1 = np.random.randint(0,100,10) # creates a array of random integers from (0 to 100)

In [16]:
arr1

array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40])

In [17]:
arr1.max() # returns the max value of arr1

95

In [19]:
arr1.min() # returns the min value of arr1

9

In [18]:
arr1.argmax() # returns the index location of the max value. 

0

In [20]:
arr1.mean() # returns the mean value of arr1

60.8

In [22]:
arr1.shape # returns the shape of the arr1 

(10,)

In [23]:
arr1.reshape((5,2))

array([[95, 11],
       [81, 70],
       [63, 87],
       [75,  9],
       [77, 40]])

In [25]:
mat = np.arange(0,100).reshape(10,10)

In [26]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [29]:
row = 7
col = 7
mat[row,col]

77

In [31]:
mat[:,1] # numbers with ending 1 in unit's digit

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [33]:
mat[:1] # from 0 to 10

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [34]:
mat[:2] # from 0 to 20

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [37]:
mat[1:4] # from 10 to 40

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [38]:
mat[2:5] # from 20 to 50 

array([[20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [44]:
mat[:,5] # numbers with ending 5 in unit's digit

array([ 5, 15, 25, 35, 45, 55, 65, 75, 85, 95])

In [47]:
mat[0:3 , 0:5] # row = 3 and columns = 5 

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24]])

In [52]:
mat[0:3 , 0:5] = 0 # reassigning the values from (0 to 3rd row and 0 to 5th column) to 0

In [53]:
mat

array([[ 0,  0,  0,  0,  0,  5,  6,  7,  8,  9],
       [ 0,  0,  0,  0,  0, 15, 16, 17, 18, 19],
       [ 0,  0,  0,  0,  0, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [54]:
new_mat = mat.copy() # creates a new copy of mat to the new_mat matrix

In [55]:
new_mat[0:6 , :] = 999 # reassigning the values to 999 from 0 - 59

In [56]:
new_mat

array([[999, 999, 999, 999, 999, 999, 999, 999, 999, 999],
       [999, 999, 999, 999, 999, 999, 999, 999, 999, 999],
       [999, 999, 999, 999, 999, 999, 999, 999, 999, 999],
       [999, 999, 999, 999, 999, 999, 999, 999, 999, 999],
       [999, 999, 999, 999, 999, 999, 999, 999, 999, 999],
       [999, 999, 999, 999, 999, 999, 999, 999, 999, 999],
       [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69],
       [ 70,  71,  72,  73,  74,  75,  76,  77,  78,  79],
       [ 80,  81,  82,  83,  84,  85,  86,  87,  88,  89],
       [ 90,  91,  92,  93,  94,  95,  96,  97,  98,  99]])