In [2]:
import numpy as np 

In [3]:
mylist = [1,2,3,4]

In [4]:
type(mylist)

list

In [5]:
arr = np.array(mylist)

In [6]:
arr

array([1, 2, 3, 4])

In [7]:
type(arr)

numpy.ndarray

In [8]:
np.arange(0,10,2) #arange(start,end,step)

array([0, 2, 4, 6, 8])

In [9]:
np.zeros(shape=(10,5)) # shape(rows ,columns)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [13]:
np.(shape=(10,5)) = 2

SyntaxError: invalid syntax (1930585179.py, line 1)

In [ ]:
type(0)

In [ ]:
type(0.)

In [ ]:
np.ones((2,4))

In [ ]:
np.random.seed(101)
arr1 = np.random.randint(0,100,10) # creates a array of random integers from (0 to 100)

In [ ]:
arr1

In [ ]:
arr1.max() # returns the max value of arr1

In [ ]:
arr1.min() # returns the min value of arr1

In [ ]:
arr1.argmax() # returns the index location of the max value. 

In [ ]:
arr1.mean() # returns the mean value of arr1

In [ ]:
arr1.shape # returns the shape of the arr1 

In [ ]:
arr1.reshape((5,2))

In [ ]:
mat = np.arange(0,100).reshape(10,10)

In [ ]:
mat

In [ ]:
row = 7
col = 7
mat[row,col]

In [ ]:
mat[:,1] # numbers with ending 1 in unit's digit

In [ ]:
mat[:1] # from 0 to 10

In [ ]:
mat[:2] # from 0 to 20

In [ ]:
mat[1:4] # from 10 to 40

In [ ]:
mat[2:5] # from 20 to 50 

In [ ]:
mat[:,5] # numbers with ending 5 in unit's digit

In [ ]:
mat[0:3 , 0:5] # row = 3 and columns = 5 

In [ ]:
mat[0:3 , 0:5] = 0 # reassigning the values from (0 to 3rd row and 0 to 5th column) to 0

In [ ]:
mat

In [ ]:
new_mat = mat.copy() # creates a new copy of mat to the new_mat matrix

In [ ]:
new_mat[0:6 , :] = 999 # reassigning the values to 999 from 0 - 59

In [ ]:
new_mat